/**
 * Writes `worker/src/words.ts` from the EFF Large Wordlist, the source of the four-word sync codes.
 *
 * Run once with `node worker/scripts/words.mjs`: it downloads the list, checks its sha256 against
 * the pinned one, drops the four hyphenated words and writes the module that the Worker imports.
 */
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export const EFF_URL = 'https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt';

/** sha256 of the file at `EFF_URL`, as downloaded on 2026-10-09 (7 776 lines). */
export const EFF_SHA256 = 'addd35536511597a02fa0a9ff1e5284677b8883b83e986e43f15a3db996b903e';

/** 7 776 words minus `drop-down`, `felt-tip`, `t-shirt` and `yo-yo`. */
export const WORD_COUNT = 7772;

const LINE = /^[1-6]{5}\t(\S+)$/;
const WORD = /^[a-z]+$/;

/**
 * The words of an EFF dice list (`11111\tword` per line), without the hyphenated ones.
 * Throws on any other line, on a word that is not lowercase ASCII and on a repeated word.
 */
export function wordsFromEff(text) {
  const lines = text.replace(/\r\n/g, '\n').replace(/\n$/, '').split('\n');
  const words = [];
  const seen = new Set();
  lines.forEach((line, index) => {
    const match = LINE.exec(line);
    if (!match) throw new Error(`Line ${index + 1} is not five dice and a word: ${line}`);
    const word = match[1];
    if (word.includes('-')) return;
    if (!WORD.test(word))
      throw new Error(`Line ${index + 1} is not a lowercase ASCII word: ${word}`);
    if (seen.has(word)) throw new Error(`Line ${index + 1} repeats a word: ${word}`);
    seen.add(word);
    words.push(word);
  });
  return words;
}

/** The source of `worker/src/words.ts`, formatted as Prettier would write it. */
export function renderWordsModule(words) {
  return [
    '/*',
    ' * EFF Large Wordlist (https://www.eff.org/dice), by Joseph Bonneau for the Electronic Frontier',
    ' * Foundation, CC BY 4.0 (https://www.eff.org/copyright). Source:',
    ` * ${EFF_URL}`,
    ' * without its four hyphenated words.',
    ' *',
    ' * Generated by worker/scripts/words.mjs: do not edit.',
    ' */',
    '',
    '/** The words of a sync code, in the order of the list. */',
    'export const WORDS: readonly string[] = [',
    ...words.map((word) => `  '${word}',`),
    '];',
    '',
    '/** The same words, to check a typed code. */',
    'export const WORD_SET: ReadonlySet<string> = new Set(WORDS);',
    '',
  ].join('\n');
}

async function main() {
  const response = await fetch(EFF_URL);
  if (!response.ok) throw new Error(`${EFF_URL} answered ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  const sha256 = createHash('sha256').update(bytes).digest('hex');
  if (sha256 !== EFF_SHA256) throw new Error(`${EFF_URL} changed: sha256 ${sha256}`);
  const words = wordsFromEff(new TextDecoder().decode(bytes));
  if (words.length !== WORD_COUNT)
    throw new Error(`Expected ${WORD_COUNT} words, got ${words.length}`);
  const target = fileURLToPath(new URL('../src/words.ts', import.meta.url));
  await writeFile(target, renderWordsModule(words));
  console.log(`Wrote ${words.length} words to ${target}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
